### ISSUE TITLE
Incorrect results for matrix multiplication

### ISSUE THREAD

**Issue by dfdx** [jw3126/ONNXRunTime.jl#21]
I may be just doing something stupid, but it looks like many operations - including Gemm/MatMul - started to produce incorrect results. Here's a reproducer. First, we create model with a single MatMul operation (I use Python here to avoid my own mistakes, but ONNX.jl essentially generates the same graph):

<details>

```python
import torch
from torch import nn


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()

    def forward(self, A, B):
        y = torch.matmul(B, A)   # reverse order since Julia does it this way
        return y


model = Net()
args = (torch.ones(1, 9),)

import numpy as np

pyA = np.array([[1, 4.],
                [2., 5],
                [3., 6]])
pyB = np.array([
                [7., 9, 11],
                [8., 10, 12]])
args = (torch.tensor(pyA), torch.tensor(pyB))
model(*args)
torch.onnx.export(model, args, "simple_net.onnx")
```

</details>

Running the model on these args gives the following result:

```python
model(*args)
# tensor([[ 58., 139.],
#         [ 64., 154.]], dtype=torch.float64)
```
Python's `onnxruntime` produces the same output:

```python
import onnxruntime as ort

ort_sess = ort.InferenceSession('simple_net.onnx')
ort_sess.run(None, {"onnx::MatMul_0": pyA, "onnx::MatMul_1": pyB})
[array([[ 58., 139.],
        [ 64., 154.]])]
```
But if I load it in Julia, the result is different: 

```julia
import ONNXRunTime as OX

function ort_run(path, ort_args...)
    model = OX.load_inference(path)
    ort_inputs = Dict([OX.input_names(model)[i] => ort_args[i] for i=1:length(ort_args)])
    return model(ort_inputs)
end

oA = [1.0 4.0; 2.0 5.0; 3.0 6.0]
oB = [7.0 9.0 11.0; 8.0 10.0 12.0]

ort_run(expanduser("~/Downloads/simple_net.onnx"), oA, oB)["2"]
# 2×2 Matrix{Float64}:
#   76.0  103.0
#  100.0  136.0
```
-----

I discovered this while porting ONNX.jl to ProtoBuf v1 in FluxML/ONNX.jl#74 , where multiple tests were failing, but also confirmed on `master` in Github Actions: [current test](https://github.com/FluxML/ONNX.jl/actions/runs/3064255243/jobs/4947186298) (failing), [3 month old test](https://github.com/FluxML/ONNX.jl/actions/runs/2602245031/jobs/4024111558) (passing). 

I don't see any changes in this repo fresher than 4 months, and the tests in ONNXRunTime itself pass, but is there a chance something has changed in published versions or artifacts that could result in this behavior?

**Comment by jw3126** [comment]
Mhh I cannot reproduce, I get the same results in julia and python. 
You have some paths that might differ?
 `expanduser("~/Downloads/simple_net.onnx")` 
and
`ort.InferenceSession('simple_net.onnx')`
maybe you loaded two different nets? Can you reproduce in a clean environment?

As a side note, that may or may not be relevant here. I found that a source of silent wrong behavior is input and output passing. I recommend always giving explicit names to inputs and outputs and double check that you pass the right tensors under the right names.

Could you make names explicit everywhere and reproduce in a clean env?

**Comment by dfdx** [comment]
Huh, indeed, running the test in a fresh Docker container gives the correct result. Yet, I can certainly reproduce it locally and in [ONNX.jl test](https://github.com/FluxML/ONNX.jl/actions/runs/3072807473/jobs/4964531044), so it must be collision of packages or other differences in the environment.

Regarding explicit names, you mean this, right?

```julia
model = OX.load_inference(path)
r = model(Dict("x1" => A, "x2" => B))["x3"]
```

**Comment by jw3126** [comment]
> Regarding explicit names, you mean this, right?

Yes and especially on the pytorch side, I recommend giving names to arguments when saving the model. I had some crazy silent wrong behavior with pytorch onnx saving.

> Huh, indeed, running the test in a fresh Docker container gives the correct result. Yet, I can certainly reproduce it locally and in [ONNX.jl test](https://github.com/FluxML/ONNX.jl/actions/runs/3072807473/jobs/4964531044), so it must be collision of packages or other differences in the environment.

That is really interesting. Can you also fix names when, saving the model in pytorch and reproduce? Maybe even make the matrices 1x2 and 2x1 if possible? When the example is as simple as possible, we can see which version combinations produce this bug.

**Comment by dfdx** [comment]
I now use this simple example to test the behavior in different contexts: 

```julia
using Test
import ONNXRunTime as OX


path = joinpath(@__DIR__, "..", "test.onnx")

A = [1.0 4.0;
     2.0 5.0;
     3.0 6.0]
B = [7.0 9.0 11.0;
     8.0 10.0 12.0]
model = OX.load_inference(path);
r = model(Dict("x1" => A, "x2" => B))["x3"]

@test r == [58.0 139.0; 64.0 154.0]
```
where `test.onnx` can be downloaded from [here](https://raw.githubusercontent.com/FluxML/ONNX.jl/no-change-branch/test/test.onnx) (I checked that Save As works fine for it). This file was generated using master branch ONNX.jl which sets names "x1" and "x2" to the inputs and "x3" to the output. Although ONNX.jl itself may have bugs, I see that the code above works fine in a fresh environment and fails in the ONNX.jl tests. 

<details>

<summary>The code I used to generate test.onnx</summary>

```julia
import ONNX.Ghost: Tape, Input
import ONNX: save, push_call!, ONNXCtx

# note: column-first, but save() will transpose re-arrange them when saving Gemm
A, B = [1.0 2.0 3.0; 4.0 5.0 6.0], [7.0 8.0; 9.0 10; 11 12]   

args = (A, B); kwargs = (;)
fn = (*)

tape = Tape(ONNXCtx())
inp = [push!(tape, Input(arg)) for arg in args]
res = push_call!(tape, fn, inp...; kwargs...)
tape.result = res
path = "test.onnx"
save(path, tape)
```

</details>

I'm currently busy at my daily job, but plan to return to this issue soon.

**Comment by jw3126** [comment]
> Although ONNX.jl itself may have bugs, I see that the code above works fine in a fresh environment and fails in the ONNX.jl tests.

Mhh could it be that ONNX.jl emits a model that has undefined behavior?

**Comment by dfdx** [comment]
It shouldn't - it's just 2 inputs and one Gemm operation. Also, I used ONNX.jl to generate the file purely for convenience - I observed the same behavior with the Python-generated file.

**Comment by dfdx** [comment]
It's even more weird than I thought! The problem was caused by Ghost.jl - removing this package fixes the test, adding it again replicates the failure. Not even loading it, but just adding it to the ONNX.jl. But not to a new empty project, there test works with both - ONNXRunTime and Ghost.

Ghost is my package, and I don't remember doing anything unusual in it. Except for maybe using IRTools, which is a kind of magic by itself. 

I don't see intersection in dependencies between Ghost and ONNXRunTime. Maybe in dependencies of dependencies, or maybe there's even third package involved. No idea. 

Anyway, I have a newer package (Umlaut.jl) which is a drop-in replacement for Ghost, and also fixes the tests.

(Maybe I should have expected some supernatural behavior when naming the package "Ghost" :thinking: )

Thank you for your help!
