### ISSUE TITLE
Incompatibility with cuDNN 1.3.1

### ISSUE THREAD

**Issue by GunnarFarneback** [jw3126/ONNXRunTime.jl#37]
The recently released cuDNN 1.3.1 bumps the CUDNN_jll dependency to 9.0, which provides `libcudnn.so.9`. This is not compatible with the ONNXRunTime CUDA extension, which needs `libcudnn.so.8` to be loaded before loading `libonnxruntime_providers_cuda.so`. Things might still work if `libcudnn.so.8` happens to be found in system libraries but that's obviously not something we want to depend on.

For future releases (until we can be compatible with CUDNN 9) we can upper bound cuDNN with
```
cuDNN = "~1.1, ~1.2, =1.3.0"
```
but I suspect we also had better retroactively cap the dependency for existing versions (0.4 and up) in the General registry. I know how to prepare a registry PR to that effect if it sounds good.

**Comment by jw3126** [comment]
Sounds good, thanks a lot! GPU support is such a pain.
